#!/bin/sh
case "$1" in
   host)
        shift 
        bash -c "$*"
        ;;
    docker)
        shift
        /usr/bin/env docker run -ti \
            --ulimit core=0 \
            --privileged \
            -v ./:/src \
            --rm \
            --name afl_fuzzing \
            aflplusplus/aflplusplus:v4.08c \
            bash -c "cd /src && bash -c \"$*\""
        ;;
    *)
        echo "Usage: $0 {host|docker}"
        exit 1
        ;;
esac
